# Site settings
title: "Liujunyi"
email: andyhome123@gmail.com
description: ""
baseurl: 
url: "http://andyhome123.github.io"
title_description: 
title_image: 
google_analytics: 
disqus_account: andyhome123
github_repository: https://github.com/andyhome123/andyhome123.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  
linkedin_link: 
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: 
footer_right:

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
